Output demo.gif

Set Shell zsh
Set FontSize 20
Set Width 1920
Set Height 1080
Set Padding 0
Set Margin 0
Set Framerate 60

Type "tuwi"
Sleep 0.5
Enter
Sleep 0.7

Type "2"
Sleep 2000ms

Type "t"
Sleep 0.3

Enter
Sleep 0.9

Type "<password>"
Sleep 0.5
Enter
Sleep 0.2

Type "1"
Sleep 0.5

Enter
Sleep 0.5

Type "j"
Sleep 0.5

Type "f"
Sleep 0.5

Type "q"
Sleep 0.5

Type "Thanks for watching!"
Sleep 0.5
